- name: Criando a instancia EC2
  local_action: ec2
    group={{ security_group }}
    instance_type={{ instance_type }}
    image={{ image }}
    wait=true
    region={{ region }}
    keypair={{ keypair }}
    count={{ count }}
  register: ec2

- name: Adicionando a instancia ao inventario temp
  add_host: name={{ item.public_ip }} groups={{ group_file }}
  with_items: "{{ ec2.instances }}"

- name: Adicionando a instancia criada no arquivo hosts
  local_action: lineinfile
    dest="./hosts"
    regexp={{ item.public_ip }}
    insertafter="[{{group_file}}]" line={{ item.public_ip }}
  with_items: "{{ ec2.instances }}"

- name: Esperando o ssh
  local_action: wait_for
    host={{ item.public_ip }}
    port=22
    state=started
  with_items: "{{ ec2.instances }}"

- name: Adicionando um nome tag na instancia
  local_action: ec2_tag resource={{ item.id }} region={{ region }} state=present
  with_items: "{{ ec2.instances }}"
  args:
    tags:
      Name: "{{ tag }}{{ item_id+1 }}"
  loop_control:
     index_var: item_id

- name: Adicionando a maquina criada no known_hosts
  shell: ssh-keyscan -H {{ item.public_ip }} >> ~/.ssh/known_hosts
  with_items: "{{ ec2.instances }}"

- name: Adicionando a instancia criada no .ssh/config
  local_action: lineinfile
    dest="~/.ssh/config"
    insertafter="## AWS" 
    line="Host {{ tag  }}{{ item_id+1 }}\n   hostname {{ item.public_ip }}\n   user {{ ssh_user }}\n   IdentityFile ~/.ssh/{{ keypair }}.pem\n\nHost {{ item.public_ip }}\n   hostname {{ item.public_ip }}\n   user {{ ssh_user }}\n   IdentityFile ~/.ssh/{{ keypair }}.pem\n\n"
  with_items: "{{ ec2.instances }}"
  loop_control:
    index_var: item_id
