---
- name: Incluindo Váriaveis
  include_vars: "vars_{{ansible_distribution_release}}.yml"

- name: Atualizando TimeZone
  timezone:
    name: America/Sao_Paulo

- name: Criando Diretorio
  file:
    path: "{{ mount_point }}"
    owner: nobody
    group: nogroup
    mode: 0777
    state: directory

- name: Adicionando ponto de montagem no /etc/fstab
  lineinfile:
    dest="/etc/fstab"
    line="{{ nfs_storage }} {{ mount_point }} nfs4 nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport 0 0"

- name: Atualizando cache do APT
  apt:
    update_cache: yes

- name: Atualizando pacotes
  apt:
    name: "*"
    state: latest    

- name: Instalando pacotes padrões
  apt:
    name: "{{ APT_PACKAGES }}"
    state: present

- name: Montando diretório
  shell:
    cmd: mount -a