version: '3.8'
services:
  wordpress:
    image: wordpress:latest
    environment:
      WORDPRESS_DB_HOST: 
      WORDPRESS_DB_NAME: 
      WORDPRESS_DB_USER: 
      WORDPRESS_DB_PASSWORD: 
    ports:
    - "80:80"
    deploy:
      replicas: 1
    volumes:
    - /media/dados/wp_data:/var/www/html
